# Problem

# An RNA string is a string formed from the alphabet containing 'A', 'C', 'G', and 'U'.

# Given a DNA string t
# corresponding to a coding strand, its transcribed RNA string u is formed by replacing all occurrences of 'T' in t with 'U' in u

# .

# Given: A DNA string t

# having length at most 1000 nt.

# Return: The transcribed RNA string of t

# .
# Sample Dataset

# GATGGAACTTGACTACGTAAATT

# Sample Output

# GAUGGAACUUGACUACGUAAAUU

DNA="GTGGTGCAAATAAACGAAGTAGATTGACGACGCAAATGGATTAGGACATGTAATCCAAAGGGCCGCTGTTGAAAACTATGCCAAGTCGAATTCCAGACGGTTCGACCTCTGCTATAAGGCGTAGCGGAACGTCATGGATAATCCTTTGTAACACTGTTTACACGTGTGGATATACGACTCTTTTCAAGATCGAGTGAGCGAATGCTCTCTTTTTTATAAATTAGCTCGCAGTATCTTGTGTGACCAATTACACACTTGAATGATGCCGAGGACAGGCACTTGCATTTACGCCACGTCACATGTGGGGCATGGGGACGTAAAACCGGCATGAAGATGGGTGCTTAAGTCGTTCTAAATTCCCGTGGACAGCCTGCAGCAGCCGGGCCTAGCGCGCTAACAGACGGTCAAGGGATACAGGTCCCTAAACCGCTGTAGGAAGGCAGTAGGATTCCTAATAGAGACAGTCACTGTGGCTCGCAATAAGCCGACTGCTAAGGGGCAGCAATAAATGTCTACAGTAAACGCATGGCAAGAACGCCCGTCCGGTACGGGAAGCCCCTAATCCTTAACAATCCGAAAGAATGTAGAAGCCACCATGCATAACCATTTGGACATTAATACGAACTCGCCCGCGGATTAGAACTTCAAATGCCCTATACTCCCAGACCATAAAGTAATATAAAGGAACTGTTCAGAAAACAGTGAGGAAGCAAAGAGCCTAGATGACGCCTTGCTATTGCAGTTAGCGTAGTTGGCCAGATTATCGACGCATGACAGTCTAGGACAAGAACCTACGGCTACTCAGATGGTTTCTGCTCCAGACCATTTGAACACTACCCATCCCTAAGCGGTATAAGATGGCCGATCCTTTGTTTGCTTCTTTGTCTGCAGAGCACTGTGACGAACTGTATCTAAGGCAGGCGTGGACGAGCCAAGGCTATAGGGCGCACTAATA"
RNA=""


RNA_code=['A','C','G'] #A C G U

for i in range (0,len(DNA)):
    if DNA[i] in RNA_code:
        RNA+=DNA[i]
    if(DNA[i]=='T'):
        RNA+='U'


print(RNA)

